const menuBtn=document.querySelector('.menu-btn');const nav=document.querySelector('.nav');
menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.14});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;document.querySelectorAll('.product-card').forEach(card=>card.classList.toggle('hidden',filter!=='all'&&card.dataset.category!==filter))}));
const stats=document.querySelector('.stats');let counted=false;new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&!counted){counted=true;document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count;let current=0;const step=Math.max(1,Math.ceil(target/45));const timer=setInterval(()=>{current=Math.min(target,current+step);el.textContent=current;if(current===target)clearInterval(timer)},28)})}},{threshold:.3}).observe(stats);
const sections=document.querySelectorAll('main section[id]');window.addEventListener('scroll',()=>{let current='inicio';sections.forEach(section=>{if(scrollY>=section.offsetTop-150)current=section.id});document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))});
document.querySelector('.quote-form').addEventListener('submit',event=>{event.preventDefault();const status=event.currentTarget.querySelector('.form-status');status.textContent='¡Gracias! Tu solicitud está lista. Te contactaremos muy pronto.';event.currentTarget.reset()});
